[package]
name = "nochfragen"
version = "0.1.0"
edition = "2024"
publish = false
default-run = "nochfragen"

[dependencies]
axum = "0.8.8"
diesel = { version = "2.3.7", features = ["sqlite", "r2d2", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15.7"
fred = "10.1.0"
time = "0.3.47"
tokio = { version = "1.52.0", features = ["rt-multi-thread"] }
tower-http = { version = "0.6.8", features = ["fs"] }
tower-sessions = "0.14.0"
tower-sessions-redis-store = "0.16.0"
scrypt = { version = "0.11.0", features = ["std", "simple"] }
serde = { version = "1.0.228", features = ["derive"] }
diesel_migrations = "2.3.1"
serde_repr = "0.1.20"
anyhow = "1.0.102"
futures = "0.3.32"
csv = "1.4.0"
